config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function (RouteBuilder $routes) {
    // Home
    $routes->connect('/', ['controller'=> 'Home', 'action'=>'index']);

    // Discussions
    $routes->connect('/discussions/', ['controller'=> 'Home', 'action'=>'index']);
    $routes->connect('/discussions/:id-:slug', ['controller'=> 'Discussion', 'action'=>'oneDiscussion'], [
        'pass'=>['id', 'slug'],
        'id' => '\d+'
    ]);
    $routes->connect('/discussions/users/:id', ['controller'=> 'Discussion', 'action'=>'allByUser'], [
        'pass'=>['id', 'slug'],
        'id' => '\d+'
    ]);

    // Utilisateurs
    $routes->connect('/users/', ['controller'=> 'User', 'action'=>'index']);
    $routes->connect('/users/:id', ['controller'=> 'User', 'action'=>'oneUserById'], [
        'pass'=>['id'],
        'id' => '\d+'
    ]);
    $routes->connect('/users/:pseudo', ['controller'=> 'User', 'action'=>'oneUserByPseudo'], [
        'pass'=>['pseudo'],
    ]);


    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    // $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    // $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/DiscussionsTable.php
<?php
namespace App\Model\Table;

use App\Model\Entity\Discussion;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Discussions Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Users
 * @property \Cake\ORM\Association\BelongsTo $Tags
 * @property \Cake\ORM\Association\HasMany $Messages
 */
class DiscussionsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('discussions');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Tags', [
            'foreignKey' => 'tag_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('Messages', [
            'foreignKey' => 'discussion_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('titre', 'create')
            ->notEmpty('titre');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'));
        $rules->add($rules->existsIn(['tag_id'], 'Tags'));
        return $rules;
    }
}

src/Controller/HomeController.php
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link      http://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use Cake\Core\Configure;
use Cake\ORM\TableRegistry;

/**
 * Static content controller
 *
 * This controller will render views from Template/Pages/
 *
 * @link http://book.cakephp.org/3.0/en/controllers/pages-controller.html
 */
class HomeController extends AppController {

    public function index() {
        $discussions = TableRegistry::get('Discussions')->find('all', ['contain' => ['Users', 'Tags', 'Messages']]);

        $this->set('discussions', $discussions);
        $this->render('Pages/default');
    }

    public function allDiscussions($id, $slug) {
        $this->render('Pages/discussions');
    }

}

src/Template/Home/Pages/default.ctp
<?php  $this->extend('/Home/Layouts/default'); ?>

<div class="jumbotron">
    <h1>Hello, world!</h1>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>

<?php foreach($discussions as $discussion): ?>
<article class="row">
    <header class="col-sm-9">
        <h1><?= $this->Html->link(
            $discussion->titre,
            ['controller' => 'Discussion', 'action' => 'oneDiscussion', $discussion->id, $discussion->titre]);
        ?></h1>
    </header>
    <aside class="col-sm-3">
        <div class="row"><?= $discussion->tag->nom ?></div>
        <div class="row">By : <?= $this->Html->link(
                $discussion->user->pseudo,
                ['controller' => 'User', 'action' => 'oneUserById', $discussion->user->id]);
            ?></div>
        <div class="row">Created : <?= $discussion->created ?></div>
        <div class="row">Modified : <?= $discussion->modified ?></div>
    </aside>
</article>
<?php endforeach; ?>

src/Template/Home/Pages/discussion.ctp
<?php
$this->extend('/Home/Layouts/default');
?>

<header class="row">
    <h1 class="col-sm-9"><?= $this->Html->link(
            $discussion->titre,
            ['controller' => 'Discussion', 'action' => 'oneDiscussion', $discussion->id, $discussion->titre]);
        ?></h1>
    <aside class="col-sm-3">
        <div class="row">By : <?= $this->Html->link(
                $discussion->user->pseudo,
                ['controller' => 'User', 'action' => 'oneUserById', $discussion->user->id]);
            ?></div>
        <div class="row"><?= $discussion->tag->nom ?></div>
        <div class="row">Created : <?= $discussion->created ?></div>
        <div class="row">Modified : <?= $discussion->modified ?></div>
    </aside>
</header>

<?php foreach ($discussion->messages as $message): ?>
    <hr>
    <article class="message" id="message-<?= $message->id ?>">
        <header class="row message-header">
            <span class="col-sm-9"><?= $this->Html->link(
                    $message->user->pseudo,
                    ['controller' => 'User', 'action' => 'oneUserById', $message->user->id]);
                ?></span>
            <aside class="col-sm-3">
                <div class="row"><a href="#message-<?= $message->id ?>">#permalink</a></div>
                <div class="row">Created : <?= $message->created ?></div>
                <div class="row">Modified : <?= $message->modified ?></div>
            </aside>
        </header>
        <div class="message-content">
            <?= $message->message ?>
        </div>
    </article>
<?php endforeach; ?>

src/Template/Home/Pages/utilisateur.ctp
<?php  $this->extend('/Home/Layouts/default'); ?>

<article class="row">
    <header class="col-sm-9">
        <h1><?= $this->Html->link(
            $user->pseudo,
            ['controller' => 'User', 'action' => 'oneUserById', $user->id]);
        ?></h1>
    </header>
    <aside class="col-sm-3">
        <div class="row"><?= $this->Html->link(
                'Discussions',
                ['controller' => 'Discussion', 'action' => 'allByUser', $user->id]);
            ?></div>
        <div class="row"><?= $this->Html->link(
                'Messages',
                ['controller' => 'Message', 'action' => 'allByUser', $user->id]);
            ?></div>
        <div class="row">Created : <?= $user->created ?></div>
        <div class="row">Modified : <?= $user->modified ?></div>
    </aside>
</article>

src/Template/Home/Pages/utilisateurs.ctp
<?php  $this->extend('/Home/Layouts/default'); ?>

<?php foreach($users as $user): ?>
<hr>
<article class="row">
    <header class="col-sm-9">
        <h1><?= $this->Html->link(
            $user->pseudo,
            ['controller' => 'User', 'action' => 'oneUserById', $user->id]);
        ?></h1>
    </header>
    <aside class="col-sm-3">
        <div class="row"><?= $this->Html->link(
                'Discussions',
                ['controller' => 'Discussion', 'action' => 'allByUser', $user->id]);
            ?></div>
        <div class="row"><?= $this->Html->link(
                'Messages',
                ['controller' => 'Message', 'action' => 'allByUser', $user->id]);
            ?></div>
        <div class="row">Created : <?= $user->created ?></div>
        <div class="row">Modified : <?= $user->modified ?></div>
    </aside>
</article>
<?php endforeach; ?>